Member:
    needLogin: 'Both'
    customerGroup: 'customer'
    extensions:
        - TOSEMember

TOSEPage:
    pageTitle: 'Ecommerce'
    pageURLSegment: 'ecommerce'

TOSEProductPage:
    pageTitle: 'Product'
    pageURLSegment: 'product'
        
TOSECategoryPage:
    pageTitle: 'Category'
    pageURLSegment: 'category'

TOSECartPage:
    pageTitle: 'Cart'
    pageURLSegment: 'cart'
        
TOSECheckoutPage:
    pageTitle: 'Checkout'
    pageURLSegment: 'checkout'
    extensions:
        - TOSECheckoutPageExtension
        
TOSECurrency:
    defaultCurrency: 'NZD'
    defaultCurrencySymbol: '$'
    multiCurrency: 'FALSE'
    currencies:
        GBP: '£'
        CNY: '¥'
        AUD: '$'
        USD: '$'
    extensions:
        - TOSECurrencyExtension
    
TOSELoginPage:
    pageTitle: 'Login'
    pageURLSegment: 'login'
        