Member:
    extensions:
        - TOSEMember

TOSEPage:
    pageTitle: 'Ecommerce'
    pageURLSegment: 'ecommerce'
    needLogin: 'Both'

TOSEProductPage:
    pageTitle: 'Product'
    pageURLSegment: 'product'
        
TOSECategoryPage:
    pageTitle: 'Category'
    pageURLSegment: 'category'

TOSECartPage:
    pageTitle: 'Cart'
    pageURLSegment: 'cart'
        
TOSECheckoutPage:
    pageTitle: 'Checkout'
    pageURLSegment: 'checkout'
        
TOSECurrency:
    currencies:
        GBP: '£'
        CNY: '¥'
        AUD: '$'
        USD: '$'
    extensions:
        - TOSECurrencyExtension
    
TOSELoginPage:
    pageTitle: 'Login'
    pageURLSegment: 'login'
        