LeftAndMain:
  extra_requirements_css:
    - tosecommerce/css/tose-admin.css
    
Member:
    extensions:
        - TOSEMember
    
TOSEProductPage:
    Title:
        "Flower"
    URLSegment:
        "flower"