Member:
#needLogin options: "Yes"/"No"/"Both"
    needLogin: 'Both'
    customerGroup: 'customer'
    extensions:
        - TOSEMember

TOSERegisterPage:
    pageTitle: 'Register'
    pageURLSegment: 'register'
    
TOSELoginPage:
    pageTitle: 'Login'
    pageURLSegment: 'login'
    
TOSEAccountPage:
    pageTitle: 'Account'
    pageURLSegment: 'account'

TOSEPage:
    pageTitle: 'Ecommerce'
    pageURLSegment: 'ecommerce'

TOSEProductPage:
    pageTitle: 'Product'
    pageURLSegment: 'product'
        
TOSECategoryPage:
    pageTitle: 'Category'
    pageURLSegment: 'category'

TOSECartPage:
    pageTitle: 'Cart'
    pageURLSegment: 'cart'
        
TOSECheckoutPage:
    pageTitle: 'Checkout'
    pageURLSegment: 'checkout'
        
TOSEPrice:
    primaryCurrency: 'NZD'
    primaryCurrencySymbol: '$'
    multiCurrency: 'FALSE'
    optionalCurrencies:
        GBP: '£'
        CNY: '¥'
        AUD: '$'
        USD: '$'
        
TOSECategory:
    extensions:
        - TOSECategoryTreeHierarchy

TOSEProduct:
    hasInventory: 'Yes'

TOSEProductAdmin:
    extra_requirements_javascript: 
#        - 'tosecom/javascript/forms/EditFormMoveCategory.js'
        - 'tosecom/javascript/forms/test.js'
    extra_requirements_css:
        - 'tosecom/css/forms/EditFormMoveCategory.css'