Member:
    extensions:
        - TOSEMember

TOSEPage:
    defaultConfig:
        pageTitle: 'Ecommerce'
        pageURLSegment: 'ecommerce'

TOSEProductPage:
    defaultConfig:
        pageTitle: 'Product'
        pageURLSegment: 'product'
        
TOSECategoryPage:
    defaultConfig:
        pageTitle: 'Category'
        pageURLSegment: 'category'

TOSECartPage:
    defaultConfig:
        pageTitle: 'Cart'
        pageURLSegment: 'cart'
        
TOSECheckoutPage:
    defaultConfig:
        pageTitle: 'Checkout'
        pageURLSegment: 'checkout'
        
TOSECurrency:
    defaultConfig:
        currencies:
            GBP: '£'
            CNY: '¥'
            AUD: '$'
            USD: '$'
    extensions:
        - TOSECurrencyExtension
        
TOSECart:
    needLogin: 'Both'
        