Member:
    needLogin: 'Both'
    customerGroup: 'customer'
    extensions:
        - TOSEMember

TOSERegisterPage:
    pageTitle: 'Register'
    pageURLSegment: 'register'
    
TOSELoginPage:
    pageTitle: 'Login'
    pageURLSegment: 'login'
    
TOSEAccountPage:
    pageTitle: 'Account'
    pageURLSegment: 'account'

TOSEPage:
    pageTitle: 'Ecommerce'
    pageURLSegment: 'ecommerce'

TOSEProductPage:
    pageTitle: 'Product'
    pageURLSegment: 'product'
        
TOSECategoryPage:
    pageTitle: 'Category'
    pageURLSegment: 'category'

TOSECartPage:
    pageTitle: 'Cart'
    pageURLSegment: 'cart'
        
TOSECheckoutPage:
    pageTitle: 'Checkout'
    pageURLSegment: 'checkout'
    defaultPaymentMethod: 'PaymentExpressPxPay'
    multiPaymentMethod: 'TRUE'    

        
TOSECurrency:
    defaultCurrency: 'NZD'
    defaultCurrencySymbol: '$'
    multiCurrency: 'FALSE'
    currencies:
        GBP: '£'
        CNY: '¥'
        AUD: '$'
        USD: '$'
    extensions:
        - TOSECurrencyExtension
        