Member:
    #needLogin options: "Yes"/"No"/"Both"
    needLogin: 'Both'
    #if need login, only members from this group can purchase. Registered user will be added in to this group
    customerGroup: 'customer'
    extensions:
        - TOSEMember
        
#Following are for page title and page url segment 
TOSERegisterPage:
    pageTitle: 'Register'
    pageURLSegment: 'register'
    
TOSELoginPage:
    pageTitle: 'Login'
    pageURLSegment: 'login'
    
TOSEAccountPage:
    pageTitle: 'Account'
    pageURLSegment: 'account'

TOSEPage:
    pageTitle: 'Ecommerce'
    pageURLSegment: 'ecommerce'

TOSEProductPage:
    pageTitle: 'Product'
    pageURLSegment: 'product'
        
TOSECategoryPage:
    pageTitle: 'Category'
    pageURLSegment: 'category'

TOSECartPage:
    pageTitle: 'Cart'
    pageURLSegment: 'cart'
        
TOSECheckoutPage:
    pageTitle: 'Checkout'
    pageURLSegment: 'checkout'

        
TOSEPrice:
    #System will use this currency to do payment
    primaryCurrency: 'NZD'    
    primaryCurrencySymbol: '$'
    #multiCurrency is only for show price, payment will still use primary currency
    multiCurrency: 'FALSE'
    optionalCurrencies:
        GBP: '£'
        CNY: '¥'
        AUD: '$'
        USD: '$'
        
TOSECategory:
    extensions:
        - TOSECategoryTreeHierarchy

TOSEProduct:
    #Control if the system has inventory feature
    hasInventory: 'Yes'

TOSEProductAdmin:
    extra_requirements_javascript: 
        - 'tosecom/javascript/forms/EditFormMoveCategory.js'
    extra_requirements_css:
        - 'tosecom/css/forms/EditFormMoveCategory.css'